#!/usr/bin/env python3
# BLUF: 각 폴더 하위 문서/폴더의 BLUF를 모아 README.md의 자동 인덱스 블록만 생성·갱신하는 결정적 스크립트(LLM 0).
"""
gen_readmes.py — BLUF 기반 README 자동 생성기 (결정적 롤업, LLM 0)

출처: 개인 도구에서 이식·검증한 BLUF 롤업 구현.
적용: BLUF 마커를 모아 폴더 README 인덱스를 결정적으로 생성한다 — DB·LLM 세션 불요.

규약(convention):
  - 모든 관리 대상 문서는 상단(앞 25줄)에 BLUF(Bottom Line Up Front) 한 줄을 둔다.
      · Markdown : 첫 부분에 `> **BLUF:** <한 줄>`  (또는 `<!-- BLUF: <한 줄> -->`)
      · 해시 주석형(.py/.yml/.toml/.sh) : `# BLUF: <한 줄>`
      · 슬래시 주석형(.js/.ts/.css)      : `// BLUF: <한 줄>`
      · JSON                            : `"_bluf": "<한 줄>"`  (주석 불가 포맷 대응)
  - README.md는 손대지 않는 "폴더 자체 설명(상단, 수기)"과, 스크립트가 관리하는
    자동 인덱스 블록(마커 사이)으로 구성된다. 인덱스 블록만 재생성되며 나머지는 보존된다.

동작:
  - 저장소 루트부터 폴더를 훑어, 숨김/시스템/제외 폴더를 건너뛴다.
  - 각 폴더에 대해: 하위 폴더(README의 BLUF)와 문서(파일의 BLUF)를 모아 인덱스 블록을 만든다.
  - README가 없으면 BLUF 자리(TODO)를 둔 새 파일을 만들고, 있으면 인덱스 블록만 교체한다.
  - 내용이 실제로 바뀐 파일만 기록한다(멱등).

사용:
  ai-harness gen-readmes           # 적용(README 갱신)
  ai-harness gen-readmes --check    # 드라이런: 변경 필요/누락 BLUF가 있으면 비영(非零) 종료
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

# ── 설정 ─────────────────────────────────────────────────────────────────────
REPO_ROOT = Path(__file__).resolve().parent.parent

# 이름이 아래에 걸리거나 '.'로 시작하는 폴더는 건너뛴다(예외처리: root의 시스템/사설 폴더).
EXCLUDE_DIR_NAMES = {"node_modules", "__pycache__", "venv", ".venv"}

# BLUF를 탐색할 텍스트 확장자.
TEXT_EXTS = {
    ".md", ".markdown", ".txt", ".json", ".jsonc", ".yaml", ".yml",
    ".toml", ".ini", ".cfg", ".py", ".js", ".ts", ".sh", ".ps1",
    ".css", ".html", ".htm",
}

# BLUF를 달 수 없는 정보성 바이너리/자산 — 이름만 README에 나열(같은 확장자 다수면 집약).
ASSET_EXTS = {
    ".pdf", ".svg", ".docx", ".doc", ".pptx", ".ppt", ".xlsx", ".xls",
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".tiff",
    ".csv", ".zip", ".mp4", ".mov", ".ipynb",
}
_ASSET_COLLAPSE_MIN = 4  # 같은 확장자 자산이 이 개수 이상이면 `*.ext N개`로 집약.

# 에이전트 설정 파일 — 지식 문서가 아니라 툴 설정. BLUF·인덱스
# 대상에서 제외한다(저장소가 관리하는 마커 블록만 실림, BLUF 요구 없음).
# 주: 저장소의 온보딩 스크립트 등에도 동일 상수를 둘 수 있다 — gen_readmes는 의존성
# 경량(LLM 0, standalone) 유지 위해 무거운 패키지를 import하지 않으므로 의도적 미러.
AGENT_CONFIG_NAMES = {"AGENTS.md", "CLAUDE.md"}

MARK_START = "<!-- BLUF-INDEX:START — auto-generated by ai-harness gen-readmes; 이 블록은 수기 편집 금지 -->"
MARK_END = "<!-- BLUF-INDEX:END -->"

_HEAD_LINES = 25  # 각 파일의 앞부분에서만 BLUF를 찾는다.

# BLUF 추출 패턴(명시적 마커만 — 오탐 방지 위해 느슨한 'BLUF:' 평문 매칭은 두지 않는다).
#   · Markdown : `> **BLUF:** …` / `<!-- BLUF: … -->`
#   · 주석형   : `# BLUF: …` / `// BLUF: …`
#   · JSON     : `"_bluf": "…"`
_BLUF_PATTERNS = [
    re.compile(r"<!--\s*BLUF:\s*(.+?)\s*-->", re.IGNORECASE),
    re.compile(r"^\s*>?\s*\*\*BLUF:\*\*\s*(.+?)\s*$", re.IGNORECASE),
    re.compile(r'"_bluf"\s*:\s*"(.+?)"', re.IGNORECASE),
    re.compile(r"^\s*(?://|#)\s*BLUF:\s*(.+?)\s*$", re.IGNORECASE),
]

TODO_PREFIX = "TODO"  # 폴더 목적 BLUF가 아직 없을 때 표시.

# 종료코드로 실패 경우를 나눈다 — 호출자(pre-commit 훅)가 처방을 덧붙일지
# 말지 정하려면 "왜 실패했나"를 알아야 한다. 손글씨 중단은 여기서 이미 완전한
# 처방을 주므로 훅이 또 말하면 같은 규범이 두 곳에 생긴다(재서술 → 드리프트).
HANDWRITTEN_ABORT = 2  # 블록 안 손글씨 — 이 스크립트가 처방까지 출력함.
DRIFT = 1              # 인덱스가 원본과 어긋남 — 재생성하면 풀린다.


def read_head(path: Path) -> list[str]:
    try:
        with path.open("r", encoding="utf-8", errors="replace") as f:
            out = []
            for i, line in enumerate(f):
                if i >= _HEAD_LINES:
                    break
                out.append(line.rstrip("\n"))
            return out
    except (OSError, UnicodeError):
        return []


def extract_bluf(path: Path) -> str | None:
    """파일 앞부분에서 BLUF 한 줄을 뽑는다. 없으면 None."""
    head = read_head(path)
    for line in head:
        for pat in _BLUF_PATTERNS:
            m = pat.search(line)
            if m:
                text = m.group(1).strip().rstrip("-> ").strip().strip('"')
                if text:
                    return text
    # 여러 줄에 걸친 HTML 주석 BLUF 대응.
    joined = "\n".join(head)
    m = re.search(r"<!--\s*BLUF:\s*(.+?)\s*-->", joined, re.IGNORECASE | re.DOTALL)
    if m:
        return " ".join(m.group(1).split())
    return None


def readme_own_bluf(folder: Path) -> str | None:
    """폴더 README의 '폴더 자체 BLUF'를 읽는다(자식 인덱스에 표시용)."""
    readme = folder / "README.md"
    if not readme.exists():
        return None
    return extract_bluf(readme)


def is_excluded_dir(d: Path) -> bool:
    name = d.name
    if name.startswith("."):
        return True
    if name in EXCLUDE_DIR_NAMES:
        return True
    return False


def is_git_ignored(path: Path) -> bool:
    """Return whether Git excludes a local-only artifact from repository indexes.

    cwd는 대상 경로의 부모(그 파일이 속한 git repo) — REPO_ROOT로 고정하면 대상이
    중첩된 다른 저장소(예: 미러 클론)에 있을 때 REPO_ROOT 저장소의 .gitignore로 오판한다."""
    parent = path.parent if path.parent.exists() else REPO_ROOT
    result = subprocess.run(
        ["git", "check-ignore", "-q", "--", str(path)],
        cwd=str(parent),
        check=False,
        capture_output=True,
    )
    return result.returncode == 0


def is_skipped_dir(d: Path) -> bool:
    """폴더를 순회·인덱스에서 건너뛸지 — 이름 규칙(시스템/사설) 또는 git-ignore(로컬 전용).

    gitignore된 폴더(로컬 스크래치 등)는 체크아웃마다 존재가 갈린다. 인덱스에 실으면
    그 폴더를 가진 사람과 아닌 사람이 서로 다른 README를 생성해 결과 자체가 오염되고,
    그 어긋남(drift)이 --check를 계속 비영으로 만들어 무관한 커밋까지 봉쇄한다.
    추적하지 않는(=관리 대상 아닌) 폴더는 생성·인덱스 양쪽에서 뺀다.

    (사고 원본: pollux-o4-labs/vector-graph-ontology#21 증상 2. 레포가 다르므로
    번호만 쓰면 엉뚱한 이슈를 가리킨다 — owner/repo까지 적어야 링크가 걸린다.)"""
    return is_excluded_dir(d) or is_git_ignored(d)


def iter_folders(root: Path):
    """제외 규칙을 지키며 폴더를 재귀적으로 순회(루트 포함)."""
    yield root
    stack = [root]
    while stack:
        cur = stack.pop()
        try:
            children = sorted(
                [p for p in cur.iterdir() if p.is_dir() and not p.is_symlink()],
                key=lambda p: p.name,
            )
        except OSError as e:
            print(f"[warn] 폴더 읽기 실패로 건너뜀(검증 누락 가능): {cur} ({e})", file=sys.stderr)
            continue
        for child in children:
            if is_skipped_dir(child):
                continue
            yield child
            stack.append(child)


def build_index_block(folder: Path, missing: list[Path]) -> str:
    """폴더의 하위 폴더/문서 BLUF를 모아 인덱스 블록 텍스트를 만든다."""
    subdirs = sorted(
        [p for p in folder.iterdir() if p.is_dir() and not p.is_symlink() and not is_skipped_dir(p)],
        key=lambda p: p.name,
    ) if folder.is_dir() else []

    docs = sorted(
        [
            p for p in folder.iterdir()
            if p.is_file()
            and p.name != "README.md"
            and p.name not in AGENT_CONFIG_NAMES
            and p.suffix.lower() in TEXT_EXTS
        ],
        key=lambda p: p.name,
    ) if folder.is_dir() else []

    lines = [MARK_START]

    if subdirs:
        lines.append("### 하위 폴더")
        for d in subdirs:
            bluf = readme_own_bluf(d)
            if bluf is None:
                desc = "(README 없음)"
            elif bluf.startswith(TODO_PREFIX):
                desc = f"_{bluf}_"
            else:
                desc = bluf
            lines.append(f"- `{d.name}/` — {desc}")
        lines.append("")

    # 아카이브 폴더(원문 수집본 색인 `_manifest.md` 보유): 번호 수집본은 BLUF 면제·집약 표기.
    is_archive = (folder / "_manifest.md").exists()
    numbered_re = re.compile(r"^\d+[-_]")

    doc_entries = []
    archived = 0
    for f in docs:
        if is_archive and numbered_re.match(f.name):
            archived += 1
            continue  # 아카이브 원문: 개별 나열·BLUF 요구 생략(색인은 _manifest.md).
        bluf = extract_bluf(f)
        if bluf is None:
            # 메타(_로 시작)·비-md는 조용히 skip, 그 외 .md 문서는 BLUF 누락 보고.
            if f.suffix.lower() in {".md", ".markdown"} and not f.name.startswith("_"):
                missing.append(f)
            continue
        doc_entries.append(f"- `{f.name}` — {bluf}")

    if doc_entries:
        lines.append("### 문서")
        lines.extend(doc_entries)
        lines.append("")

    if is_archive and archived:
        lines.append(f"### 원문 수집본")
        lines.append(f"- `NN-*.md` {archived}건 — 색인·fetch 결과는 `_manifest.md`, 실제 예시는 `_examples.md` 참조")
        lines.append("")

    # 정보성 바이너리/자산(BLUF 불가): 이름만 나열, 같은 확장자 다수면 집약.
    assets = sorted(
        [p for p in folder.iterdir()
         if p.is_file()
         and not p.is_symlink()
         and p.suffix.lower() in ASSET_EXTS
         and not is_git_ignored(p)],
        key=lambda p: p.name,
    ) if folder.is_dir() else []
    if assets:
        ext_counts = Counter(p.suffix.lower() for p in assets)
        collapsed: set[str] = set()
        asset_lines: list[str] = []
        for a in assets:
            ext = a.suffix.lower()
            if ext_counts[ext] >= _ASSET_COLLAPSE_MIN:
                if ext not in collapsed:
                    collapsed.add(ext)
                    asset_lines.append(f"- `*{ext}` {ext_counts[ext]}개")
            else:
                asset_lines.append(f"- `{a.name}`")
        lines.append("### 기타 파일 (BLUF 없음)")
        lines.extend(asset_lines)
        lines.append("")

    lines.append(MARK_END)
    return "\n".join(lines).rstrip() + "\n"


def handwritten_in_block(old_content: str) -> list[str]:
    """마커 블록 안에서 이 스크립트가 만들지 않은 줄을 찾는다.

    블록은 교체 대상이라 여기 있는 줄은 재생성 때 사라진다. 생성물은 형식이
    고정(`- \\`이름\\` — 설명` / `### 제목` / 빈 줄)이므로, 그 형식을 벗어난 줄은
    사람·에이전트가 손으로 넣은 것이다. 지우기 전에 멈추라고 이 목록을 쓴다.
    """
    if MARK_START not in old_content or MARK_END not in old_content:
        return []
    inner = old_content.split(MARK_START, 1)[1].split(MARK_END, 1)[0]
    return [
        line for line in inner.split("\n")
        if line.strip()
        and not line.startswith("- `")
        and not line.startswith("###")
    ]


def compose_readme(folder: Path, index_block: str) -> str:
    """기존 README의 수기 부분을 보존하며 인덱스 블록만 교체/삽입."""
    readme = folder / "README.md"
    label = folder.name if folder != REPO_ROOT else REPO_ROOT.name

    if readme.exists():
        content = readme.read_text(encoding="utf-8", errors="replace")
        if MARK_START in content and MARK_END in content:
            head = content.split(MARK_START, 1)[0].rstrip()
            tail = content.split(MARK_END, 1)[1].lstrip()
            parts = [head, "", index_block.rstrip()]
            if tail:
                parts += ["", tail.rstrip()]
            return "\n".join(parts).rstrip() + "\n"
        # 마커 없는 기존 README: 전체를 보존하고 인덱스 블록을 뒤에 덧붙인다(비파괴).
        return content.rstrip() + "\n\n" + index_block.rstrip() + "\n"

    # 신규 README: 폴더 목적 BLUF 자리(TODO)를 둔다.
    header = f"> **BLUF:** {TODO_PREFIX} — `{label}/` 폴더 목적을 한 줄로 채우세요."
    return header + "\n\n" + index_block.rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="BLUF 기반 README 자동 생성기")
    ap.add_argument("--check", action="store_true",
                    help="드라이런: 변경 필요/누락 BLUF가 있으면 비영 종료(파일 미수정)")
    ap.add_argument("--root", default=str(REPO_ROOT), help="저장소 루트 경로")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    changed: list[Path] = []
    missing_bluf: list[Path] = []
    todo_folders: list[Path] = []
    doomed: list[tuple[Path, list[str]]] = []
    pending: list[tuple[Path, str]] = []

    for folder in iter_folders(root):
        index_block = build_index_block(folder, missing_bluf)
        new_content = compose_readme(folder, index_block)
        readme = folder / "README.md"

        old_content = readme.read_text(encoding="utf-8", errors="replace") if readme.exists() else None
        if old_content is not None:
            hand = handwritten_in_block(old_content)
            if hand:
                doomed.append((readme, hand))
        if old_content != new_content:
            changed.append(readme)
            pending.append((readme, new_content))

        if f"**BLUF:** {TODO_PREFIX}" in new_content:
            todo_folders.append(folder)

    # 손으로 쓴 줄이 하나라도 블록 안에 있으면 **아무것도 쓰지 않고 멈춘다.**
    # 쓰고 나서 알리면 이미 지워진 뒤라 알림이 소용없다 — 파괴는 되돌릴 수
    # 있어야 알림이 값어치를 갖는다. 스캔을 다 돌린 뒤 판정하는 이유는, 한
    # 폴더가 걸렸는데 앞 폴더는 이미 써버리는 반쪽 실행을 막기 위해서다.
    if doomed:
        print("\n[gen_readmes] 중단 — 자동생성 블록 안에 손으로 쓴 줄이 있다.",
              file=sys.stderr)
        print("  재생성하면 아래 줄들이 사라진다. 지우기 전에 멈췄다.",
              file=sys.stderr)
        for p, lines in doomed:
            print(f"\n  {p.relative_to(root).as_posix()}", file=sys.stderr)
            for line in lines:
                print(f"      {line}", file=sys.stderr)
        print(f"""
  줄이거나 형식을 고치지 마라 — **먼저 어디로 갈지 정하라.** 목적지가 그 자리의
  상한을 정하므로, 목적지 없이 축약하면 형식이 안 맞아 또 고치게 된다.

  그 내용이 특정 문서에 관한 것이면
      → 그 문서의 BLUF 한 줄을 고쳐라. 인덱스는 거기서 파생된다.
  이 폴더 자체의 목적이면
      → README 맨 위 BLUF 한 줄에 써라(블록 밖이라 재생성이 보존한다).
  둘 다 아니면
      → README에 있을 내용이 아니다. 원본 문서 본문으로 옮겨라.

  옮긴 뒤 이 명령을 다시 돌려라.""", file=sys.stderr)
        return HANDWRITTEN_ABORT

    if not args.check:
        for readme, new_content in pending:
            readme.write_text(new_content, encoding="utf-8", newline="\n")

    # ── 리포트 ────────────────────────────────────────────────────────────────
    rel = lambda p: p.relative_to(root).as_posix()
    print(f"[gen_readmes] 루트: {root}")
    print(f"  변경{'(필요)' if args.check else ''} README: {len(changed)}")
    for p in changed:
        print(f"    ~ {rel(p)}")
    if missing_bluf:
        print(f"  BLUF 누락 문서(.md): {len(missing_bluf)}")
        for p in sorted(set(missing_bluf)):
            print(f"    ! {rel(p)}")
    if todo_folders:
        print(f"  폴더 목적 BLUF 미작성(README 상단 TODO): {len(todo_folders)}")
        for p in todo_folders:
            print(f"    ? {rel(p) if p != root else '.'}")

    if args.check and (changed or missing_bluf):
        print("[gen_readmes] --check: 갱신 필요 또는 BLUF 누락 존재 → 비영 종료")
        return DRIFT
    return 0


if __name__ == "__main__":
    sys.exit(main())
