#!/usr/bin/env python3
# BLUF: 모든 저장소가 같이 들고 가야 할 판정 축 문구(정본은 이 패키지)를 대상 AGENTS.md에 마커로 감싸 주입 — `--check`로 어긋남을 게이트한다.
"""AGENTS.md 공용 안내 주입기.

`AGENTS.md`는 여러 도구가 함께 읽는 공개 표준이고 자체 완결 파일을 상정한다
— `@AGENTS.md` 같은 불러오기 표기는 일부 도구만 해석해 나머지에서는 그냥
글자로 보인다. 그래서 모든 저장소가 같이 들고 가야 할 문구는 **원문 그대로**
각 저장소의 AGENTS.md에 들어가야 한다.

정본은 이 모듈의 `_CONTENT` 하나다 — 각 저장소가 손으로 옮겨 적으면 정본이
갈린다. 이 명령이 그 정본을 마커(`AGENTS-COMMON:START`/`END`)로 감싸
주입하고, `--check`가 이후의 어긋남(정본이 바뀌었는데 재주입을 안 했거나,
블록 안을 손으로 고친 경우)을 게이트한다.

마커 탐색·중복 마커 가드·마커 쌍 교체(또는 없으면 끝에 덧붙임)·원자적 쓰기는
`gen_readmes.py`가 README 인덱스에 대해 이미 푼 문제라 `marker_splice.py`
(공유 유틸)를 그대로 쓴다 — 갈라 둔 것은 블록 **내용** 판정 하나뿐이다.
README 인덱스는 폴더마다 내용이 달라 형태로 추정할 수밖에 없지만, 이 블록은
모든 저장소가 같은 정본을 받으므로 **정확 일치**로 잰다(다르면 손댄 것).

**"정본과 다르다"에는 서로 다른 두 사건이 섞인다** — (a) 사람이 블록 안을
직접 고쳤다(잡아야 한다) (b) 아무도 안 건드렸는데 그 뒤 `_CONTENT`가
바뀌었다(그냥 낡음이다, 잡으면 안 된다). "블록 내용 대 지금 `_CONTENT`"
하나로만 비교하면 이 둘을 못 가른다(실사고: 적대검증 BLOCKER — 정본만
고치고 재주입했더니 손편집으로 오판해 멈췄다). 그래서 블록 안에 **쓰기
시점 해시**(`hash=` 주석)를 같이 심는다 — "지금 정본과 같은가"가 아니라
"이 도구가 마지막으로 쓴 그대로인가"를 재면 (a)·(b)가 갈린다: 해시가
맞으면 정본이 바뀌었어도 (b)라 조용히 재생성하고, 해시가 안 맞으면 그
사이 누가 글자를 건드린 것이니 (a)로 멈춘다.

사용:
  ai-harness gen-agents-common          # 주입/갱신
  ai-harness gen-agents-common --check  # 드라이런: 없거나 어긋나면 비영 종료
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

from ai_harness.config import target_root
from ai_harness.marker_splice import compile_markers
from ai_harness.marker_splice import extract_block as _extract_block
from ai_harness.marker_splice import marker_occurrences as _marker_occurrences
from ai_harness.marker_splice import splice as _splice
from ai_harness.marker_splice import write_atomically as _write_atomically
from ai_harness.marker_splice import write_lf as _write_lf

TARGET_RELPATH = Path("AGENTS.md")

MARK_START = (
    "<!-- AGENTS-COMMON:START — auto-generated by ai-harness gen-agents-common; "
    "이 블록은 수기 편집 금지 -->"
)
MARK_END = "<!-- AGENTS-COMMON:END -->"
_MARK_START_RE, _MARK_END_RE = compile_markers(MARK_START, MARK_END)

# 정본 문구 — 모든 소비 저장소가 같게 받는다. 예시는 붙이지 않는다: 어긴
# 사례를 달면 그와 닮은 것만 찾게 되어 시야가 좁아진다(적대리뷰 지적).
# 축 여섯의 뜻은 고정이고 문구만 다듬을 수 있다 — 저장소마다 다를 내용은
# 넣지 않는다(넣으면 주입 자체가 불가능해진다).
_CONTENT = """## 산출물 판정 축

작업을 마쳤다고 보고하기 전에 아래 여섯 축으로 스스로 대조하라.

- 기능 — 하려던 일이 되는가
- 비기능 — 빠르고 안정적이며 되돌릴 수 있는가
- 확장성 — 다음 항목이 선언 하나로 붙는가, 코드 분기로 붙는가
- 유지보수성 — 같은 판단을 한 곳에만 두었는가
- 관측가능성 — 이 결함을 다음에는 재현 없이 판정할 수 있는가
- 사용성 — 설명 없이 쓸 수 있는가"""

# 종료코드 — gen_readmes.py와 같은 값·같은 뜻(호출자가 pre-commit 훅이라 뜻이
# 어긋나면 처방을 잘못 붙인다). 이 모듈 혼자 쓰는 이름공간이라 값을 gen_readmes와
# import로 공유하지 않는다(우연히 같은 수치를 골랐을 뿐 두 모듈이 결합될
# 이유가 없다 — 결합하면 한쪽 종료코드를 못 늘린다).
DRIFT = 1              # 블록이 없거나 정본과 다름 — 재생성하면 풀린다.
HANDWRITTEN_ABORT = 2  # 블록 안 손글씨 — 쓰기 전에 멈춘다.
DUPLICATE_MARKERS = 3  # 마커 쌍이 온전한 한 쌍이 아님(중복·짝 안 맞음).

# 쓰기 시점 해시 주석 — MARK_START 자신에는 못 심는다(마커는 `marker_splice`가
# `re.escape`로 리터럴 통째 매칭하는 상수라, 실행마다 달라지는 값을 그 문자열
# 안에 넣으면 다음 실행이 자기가 쓴 마커조차 못 찾는다). 그래서 블록 **내용**의
# 맨 앞줄로 심는다 — `marker_splice`는 안 건드리면서 `extract_block`이 돌려주는
# 내부 텍스트 안에서 이 모듈이 직접 떼어 본다.
_HASH_PREFIX = "<!-- gen-agents-common:hash="
_HASH_LINE_RE = re.compile(r"^<!-- gen-agents-common:hash=([0-9a-f]{12}) -->\s*$", re.MULTILINE)


def _content_hash(body: str) -> str:
    """정본 문구의 무결성 해시(sha256 앞 12자, 양끝 공백 제외).

    "지금 정본이 무엇인가"가 아니라 "이 도구가 마지막으로 쓴 그 글자
    그대로인가"를 증명하는 값이다 — `_CONTENT`가 바뀌어도 이미 쓰인 파일
    안의 이 해시는 안 바뀐다.
    """
    return hashlib.sha256(body.strip().encode("utf-8")).hexdigest()[:12]


def _split_hash_and_body(inner: str) -> tuple[str | None, str]:
    """블록 내부 텍스트에서 해시 주석 줄과 나머지 본문(축 목록)을 가른다.

    해시 줄이 없으면(이 필드를 아직 모르던 구버전 산출물 등) `None` — 이때는
    "마지막으로 쓴 그대로인가"를 증명할 방법이 없으므로, 증명 못 하면 통과
    시키지 않는다는 기본값으로 되돌아간다(호출측이 정확 일치로 처리).
    """
    m = _HASH_LINE_RE.search(inner)
    if not m:
        return None, inner.strip()
    body = inner[:m.start()] + inner[m.end():]
    return m.group(1), body.strip()


def build_block(content: str | None = None) -> str:
    """마커를 포함한 완결 블록 텍스트 — `marker_splice.splice`는 이 문자열째로
    삽입/교체한다(마커는 splice가 아니라 여기서 찍는다).

    `content`를 안 주면(기본) **호출 시점**의 `_CONTENT`를 쓴다 — 함수
    시그니처 기본값(`= _CONTENT`)으로 박으면 정의 시점 값이 굳어 테스트가
    `_CONTENT`를 monkeypatch해도 안 먹는다.
    """
    if content is None:
        content = _CONTENT
    hash_line = f"{_HASH_PREFIX}{_content_hash(content)} -->"
    return "\n".join([MARK_START, "", hash_line, "", content, "", MARK_END]) + "\n"


def handwritten_edit(old_content: str) -> str | None:
    """블록 안을 사람이 고쳤으면 그 현재 내용을(안내 출력용) 반환, 아니면 None.

    **"정본과 다르다"만으로는 판정하지 않는다** — 정본(`_CONTENT`)이 바뀌면
    블록을 아무도 안 건드려도 무조건 달라지기 때문이다(회귀: 적대검증
    BLOCKER). 대신 블록에 심어둔 쓰기 시점 해시로 "이 도구가 마지막으로 쓴
    그대로인가"를 잰다.

    - 해시가 몸통(축 목록)과 일치 → 정본이 그 뒤 바뀌었어도 손편집이 아니라
      그냥 낡음이다. 조용히 재생성해도 안전하므로 None.
    - 해시가 없는 구버전 산출물 → 증명할 수 없으니 이전 방식대로 정확 일치로
      되돌아간다(하위호환, 안전 기본값 — 증명 못 하면 통과시키지 않는다).
    - 그 외(해시가 있는데 안 맞음) → 쓰인 뒤 글자가 바뀐 것이니 손편집.
    """
    inner = _extract_block(old_content, _MARK_START_RE, _MARK_END_RE)
    if inner is None:
        return None
    stored_hash, body = _split_hash_and_body(inner)
    if stored_hash is not None:
        return None if stored_hash == _content_hash(body) else body
    return None if body == _CONTENT.strip() else body


def compose(content: str | None) -> str:
    """대상 AGENTS.md 전체 텍스트 — 마커 있으면 그 쌍을 교체, 없으면 기존
    내용 끝에 덧붙임, 파일 자체가 없으면 블록만.

    새로 짓는 블록은 항상 **현재** `_CONTENT`와 그 해시를 담는다 — 이 함수는
    "이제 이 내용으로 확정해 쓴다"는 뜻이므로(호출 전에 `handwritten_edit`가
    이미 안전하다고 판정했다), 낡은 해시를 그대로 들고 갈 이유가 없다.
    """
    block = build_block()
    if content is None:
        return block
    return _splice(content, block, _MARK_START_RE, _MARK_END_RE)


def _print_handwritten_abort(path: Path, current: str) -> None:
    print(f"\n[gen_agents_common] 중단 — {path}의 자동생성 블록 안을 손으로 고쳤다.",
          file=sys.stderr)
    print("  재생성하면 아래 내용이 사라진다. 지우기 전에 멈췄다.\n", file=sys.stderr)
    for line in current.splitlines():
        print(f"    {line}", file=sys.stderr)
    print(
        "\n  이 블록은 모든 저장소가 같은 정본을 받는 공용 문구다 — 저장소별로"
        "\n  고칠 대상이 아니다. 내용을 바꾸고 싶으면 이 패키지(ai-harness)의"
        "\n  gen_agents_common._CONTENT를 고쳐 전체 소비 저장소에 다시 뿌려라.",
        file=sys.stderr,
    )


def main(argv: list[str] | None = None, prog: str | None = None) -> int:
    ap = argparse.ArgumentParser(prog=prog, description="AGENTS.md 공용 안내 주입기")
    ap.add_argument("--check", action="store_true",
                    help="드라이런: 없거나 어긋나면 비영 종료(파일 미수정)")
    ap.add_argument("--root", default=None,
                    help="저장소 루트 경로(기본: 대상 저장소 git 루트)")
    args = ap.parse_args(argv)

    root = Path(args.root).resolve() if args.root else target_root()
    target = root / TARGET_RELPATH

    content = target.read_text(encoding="utf-8") if target.is_file() else None

    if content is not None:
        n_start, n_end = _marker_occurrences(content, _MARK_START_RE, _MARK_END_RE)
        # 정상은 (0, 0)이거나 (1, 1)뿐이다 — gen_readmes.py와 같은 불변식.
        if (n_start, n_end) not in {(0, 0), (1, 1)}:
            print(
                f"[gen_agents_common] 중단 — {target}의 자동생성 마커가 온전한 "
                f"한 쌍이 아니다(START {n_start}회, END {n_end}회). 여분을 지우거나 "
                f"짝을 맞춘 뒤 다시 돌려라.",
                file=sys.stderr,
            )
            return DUPLICATE_MARKERS

        current = handwritten_edit(content)
        if current is not None:
            _print_handwritten_abort(target, current)
            return HANDWRITTEN_ABORT

    new_content = compose(content)

    if args.check:
        if content is None or content != new_content:
            print(
                f"[gen_agents_common] 드리프트 — {target}이 정본과 다르다"
                f"(공용 블록이 없거나 낡았다) — `ai-harness gen-agents-common`으로 갱신하라.",
                file=sys.stderr,
            )
            return DRIFT
        print(f"[gen_agents_common] {target} 최신.")
        return 0

    if content == new_content:
        print(f"[gen_agents_common] {target} 최신 — 변경 없음.")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    _write_atomically(target, new_content, write=_write_lf)
    print(f"[gen_agents_common] {target} 생성/갱신.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
