#!/usr/bin/env python3
# BLUF: 각 폴더 하위 문서/폴더의 BLUF를 모아 README.md의 자동 인덱스 블록만 생성·갱신하는 결정적 스크립트(LLM 0).
"""
gen_readmes.py — BLUF 기반 README 자동 생성기 (결정적 롤업, LLM 0)

출처: 개인 도구에서 이식·검증한 BLUF 롤업 구현.
적용: BLUF 마커를 모아 폴더 README 인덱스를 결정적으로 생성한다 — DB·LLM 세션 불요.

규약(convention):
  - 모든 관리 대상 문서는 상단(앞 25줄)에 BLUF(Bottom Line Up Front) 한 줄을 둔다.
      · Markdown : 첫 부분에 `> **BLUF:** <한 줄>`  (또는 `<!-- BLUF: <한 줄> -->`)
      · 해시 주석형(.py/.yml/.toml/.sh) : `# BLUF: <한 줄>`
      · 슬래시 주석형(.js/.ts/.css)      : `// BLUF: <한 줄>`
      · JSON                            : `"_bluf": "<한 줄>"`  (주석 불가 포맷 대응)
  - README.md는 손대지 않는 "폴더 자체 설명(상단, 수기)"과, 스크립트가 관리하는
    자동 인덱스 블록(마커 사이)으로 구성된다. 인덱스 블록만 재생성되며 나머지는 보존된다.

동작:
  - 저장소 루트부터 폴더를 훑어, 숨김/시스템/제외 폴더를 건너뛴다.
  - 각 폴더에 대해: 하위 폴더(README의 BLUF)와 문서(파일의 BLUF)를 모아 인덱스 블록을 만든다.
  - README가 없으면 BLUF 자리(TODO)를 둔 새 파일을 만들고, 있으면 인덱스 블록만 교체한다.
  - 내용이 실제로 바뀐 파일만 기록한다(멱등).

사용:
  ai-harness gen-readmes           # 적용(README 갱신)
  ai-harness gen-readmes --check    # 드라이런: 변경 필요/누락 BLUF가 있으면 비영(非零) 종료
  ai-harness gen-readmes --staged   # 스테이징된 경로가 속한 폴더(+조상)만 대상
  ai-harness gen-readmes --check --staged  # pre-commit 훅: 이번 커밋이 바꿀 수
                                            # 있는 README만 검사(다른 레인 어긋남으로 안 막힘)
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from collections import Counter
from functools import lru_cache
from pathlib import Path

from ai_harness.config import target_root

# ── 설정 ─────────────────────────────────────────────────────────────────────
# 번들 패키지의 src/ 경로 — 루트 기본값이 아니라 git-ignore 판정의 폴백 cwd로만 쓴다.
# (루트 기본값은 대상 저장소 git 루트 = target_root, main 참조.)
REPO_ROOT = Path(__file__).resolve().parent.parent

# 이름이 아래에 걸리거나 '.'로 시작하는 폴더는 건너뛴다(예외처리: root의 시스템/사설 폴더).
EXCLUDE_DIR_NAMES = {"node_modules", "__pycache__", "venv", ".venv"}

# BLUF를 탐색할 텍스트 확장자.
TEXT_EXTS = {
    ".md", ".markdown", ".txt", ".json", ".jsonc", ".yaml", ".yml",
    ".toml", ".ini", ".cfg", ".py", ".js", ".ts", ".sh", ".ps1",
    ".css", ".html", ".htm",
}

# BLUF를 달 수 없는 정보성 바이너리/자산 — 이름만 README에 나열(같은 확장자 다수면 집약).
ASSET_EXTS = {
    ".pdf", ".svg", ".docx", ".doc", ".pptx", ".ppt", ".xlsx", ".xls",
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".tiff",
    ".csv", ".zip", ".mp4", ".mov", ".ipynb",
}
_ASSET_COLLAPSE_MIN = 4  # 같은 확장자 자산이 이 개수 이상이면 `*.ext N개`로 집약.

# 에이전트 설정 파일 — 지식 문서가 아니라 툴 설정. BLUF·인덱스
# 대상에서 제외한다(저장소가 관리하는 마커 블록만 실림, BLUF 요구 없음).
# 주: 저장소의 온보딩 스크립트 등에도 동일 상수를 둘 수 있다 — gen_readmes는 의존성
# 경량(LLM 0, standalone) 유지 위해 무거운 패키지를 import하지 않으므로 의도적 미러.
AGENT_CONFIG_NAMES = {"AGENTS.md", "CLAUDE.md"}

MARK_START = "<!-- BLUF-INDEX:START — auto-generated by ai-harness gen-readmes; 이 블록은 수기 편집 금지 -->"
MARK_END = "<!-- BLUF-INDEX:END -->"

# **줄 시작 앵커가 핵심이다** — 문장 중간 인용은 줄을 시작하지 않으므로 이
# 앵커에 안 걸린다. 이 처방의 근거·실사고 상세는 check_doc_form.py의
# `_AUTOGEN_START`/`_AUTOGEN_END` 주석이 정본이다. 정규식 자체는 공유하지
# 않는다 — 이쪽은 전체 텍스트를 오프셋으로 훑고 저쪽은 줄 단위로 보아
# 매칭 단위가 다르다. 공유되는 것은 처방이지 코드가 아니다.
_MARK_START_RE = re.compile(r"^[ \t]*" + re.escape(MARK_START), re.MULTILINE)
_MARK_END_RE = re.compile(r"^[ \t]*" + re.escape(MARK_END), re.MULTILINE)

_HEAD_LINES = 25  # 각 파일의 앞부분에서만 BLUF를 찾는다.

# BLUF 추출 패턴(명시적 마커만 — 오탐 방지 위해 느슨한 'BLUF:' 평문 매칭은 두지 않는다).
#   · Markdown : `> **BLUF:** …` / `<!-- BLUF: … -->`
#   · 주석형   : `# BLUF: …` / `// BLUF: …`
#   · JSON     : `"_bluf": "…"`
_BLUF_PATTERNS = [
    re.compile(r"<!--\s*BLUF:\s*(.+?)\s*-->", re.IGNORECASE),
    re.compile(r"^\s*>?\s*\*\*BLUF:\*\*\s*(.+?)\s*$", re.IGNORECASE),
    re.compile(r'"_bluf"\s*:\s*"(.+?)"', re.IGNORECASE),
    re.compile(r"^\s*(?://|#)\s*BLUF:\s*(.+?)\s*$", re.IGNORECASE),
]

TODO_PREFIX = "TODO"  # 폴더 목적 BLUF가 아직 없을 때 표시.

# 종료코드로 실패 경우를 나눈다 — 호출자(pre-commit 훅)가 처방을 덧붙일지
# 말지 정하려면 "왜 실패했나"를 알아야 한다. 손글씨 중단은 여기서 이미 완전한
# 처방을 주므로 훅이 또 말하면 같은 규범이 두 곳에 생긴다(재서술 → 드리프트).
HANDWRITTEN_ABORT = 2  # 블록 안 손글씨 — 이 스크립트가 처방까지 출력함.
DRIFT = 1              # 인덱스가 원본과 어긋남 — 재생성하면 풀린다.
# 마커 쌍(START/END)이 한 README에 2개 이상 — split(...,1)은 항상 첫 쌍만 보므로
# 나머지는 영영 낡은 채 방치되고 그 상태를 --check가 "이상 없음"이라 오판할 수
# 있다. DRIFT·HANDWRITTEN_ABORT와 겹치면 호출자가 원인을 못 가르므로 별도 코드.
DUPLICATE_MARKERS = 3
# 쓰기 도중 OS 오류(권한 등) — 반쪽 실행 크래시. 파이썬 기본 종료코드(1)로 죽으면
# DRIFT(=1)와 겹쳐 pre-commit이 "gen-readmes를 돌려라"는 엉뚱한 처방을 낸다.
WRITE_FAILURE = 4



def _write_lf(path: Path, content: str) -> None:
    """줄바꿈을 LF로 고정해 쓴다 — 생성물이 플랫폼마다 달라지면 안 된다.

    `Path.write_text`의 `newline` 인자는 3.10부터라 선언 하한(3.9)에서
    TypeError를 낸다. `open`의 같은 인자는 오래전부터 있어 그것을 쓴다.
    """
    with path.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)

def read_head(path: Path) -> list[str]:
    try:
        with path.open("r", encoding="utf-8", errors="replace") as f:
            out = []
            for i, line in enumerate(f):
                if i >= _HEAD_LINES:
                    break
                out.append(line.rstrip("\n"))
            return out
    except (OSError, UnicodeError):
        return []


def extract_bluf(path: Path) -> str | None:
    """파일 앞부분에서 BLUF 한 줄을 뽑는다. 없으면 None."""
    head = read_head(path)
    for line in head:
        for pat in _BLUF_PATTERNS:
            m = pat.search(line)
            if m:
                # 종결 기호는 통째로 뗀다 — `rstrip`은 인자를 문자 집합으로
                # 읽어 끝의 꺾쇠·붙임표·공백을 문자 단위로 깎았다. 그래서
                # BLUF가 자리표시자로 끝나면 닫는 꺾쇠까지 잘렸다(실측: 폼
                # 넷의 인덱스 항목이 그렇게 생성되어 있었다).
                text = m.group(1).strip().removesuffix("-->").strip().strip('"')
                if text:
                    return text
    # 여러 줄에 걸친 HTML 주석 BLUF 대응.
    joined = "\n".join(head)
    m = re.search(r"<!--\s*BLUF:\s*(.+?)\s*-->", joined, re.IGNORECASE | re.DOTALL)
    if m:
        return " ".join(m.group(1).split())
    # YAML frontmatter의 description: — 에이전트 정의(.claude/agents/*.md 계열)는
    # BLUF 골격 대신 frontmatter를 쓴다(docs_format/agent-def.md 폼과 정합). 그
    # description을 인덱스 항목으로 삼아 BLUF 요구와 충돌하지 않게 한다.
    if head and head[0].strip() == "---":
        for line in head[1:]:
            if line.strip() == "---":
                break
            m = re.match(r"\s*description:\s*(.+?)\s*$", line)
            if m:
                return m.group(1).strip().strip('"').strip("'")
    return None


def _read_readme(readme: Path) -> str | None:
    """README 원문을 엄격 UTF-8로 읽는다(없으면 None). 실패하면 UnicodeDecodeError를
    호출측에 그대로 올린다 — 여기서 삼키면 안 된다.

    `read_head`(BLUF 추출)는 읽기 전용이라 errors="replace"를 그대로 둔다(최악이
    인덱스 표시 문구 한 글자 뭉개짐). 이 함수가 읽은 내용은 그대로 되쓰기
    때문에 다르다 — replace로 읽으면 원본 바이트(CP949 한글 등)가 대체문자
    (U+FFFD)로 굳어 재저장 시 영구 손실된다. 엄격 디코드로 실패를 조기에 예외로
    드러내 호출측이 쓰기 전에 건너뛰게 한다.
    """
    if not readme.exists():
        return None
    return readme.read_text(encoding="utf-8")


def _write_readme_atomically(readme: Path, content: str) -> None:
    """같은 폴더 임시 파일에 쓴 뒤 제자리 교체한다 — 대상은 늘 옛 내용이거나 새
    내용이고, 잘린 중간 상태가 될 수 없다.

    `write_text`는 원자적이지 않다. 열기는 성공했는데 디스크가 차거나 I/O가
    끊기면 그 파일이 반쪽으로 남는다 — 이 도구가 못박은 "반쪽 실행이 제일
    나쁘다"를 정작 파일 하나 안에서 어기는 자리였다. 임시 파일을 **같은 폴더**에
    두는 것이 핵심이다(다른 파일시스템이면 교체가 원자적이지 않다).

    실패하면 임시 파일을 치우고 예외를 그대로 올린다 — 대상은 손대지 않은 채다.
    """
    tmp = readme.with_name(f".{readme.name}.tmp")
    try:
        _write_lf(tmp, content)
        os.replace(tmp, readme)
    except OSError:
        tmp.unlink(missing_ok=True)
        raise


def marker_occurrences(content: str) -> tuple[int, int]:
    """START·END 마커가 줄 시작 앵커 기준으로 각각 몇 번 나타나는지.

    정상은 (0, 0)이거나 (1, 1)뿐이다 — 블록이 없거나, 온전한 한 쌍이거나.
    나머지는 사람이 봐야 할 상태다. 쌍이 여럿이면(병합 사고 등) 첫 쌍만 갱신되고
    나머지가 낡은 채 남고, 짝이 안 맞으면(START만·END만) 고아 마커 뒤에 새 블록이
    덧붙는다. 짝이 안 맞는 경우는 실제로 생긴다 — 마커를 인용부호로 감싸면
    START는 줄 시작 앵커에 안 걸리고 END만 걸린다.
    """
    return (
        sum(1 for _ in _MARK_START_RE.finditer(content)),
        sum(1 for _ in _MARK_END_RE.finditer(content)),
    )


def readme_own_bluf(folder: Path) -> str | None:
    """폴더 README의 '폴더 자체 BLUF'를 읽는다(자식 인덱스에 표시용)."""
    readme = folder / "README.md"
    if not readme.exists():
        return None
    return extract_bluf(readme)


def is_excluded_dir(d: Path) -> bool:
    name = d.name
    if name.startswith("."):
        return True
    if name in EXCLUDE_DIR_NAMES:
        return True
    return False


@lru_cache(maxsize=None)
def is_git_ignored(path: Path) -> bool:
    """Return whether Git excludes a local-only artifact from repository indexes.

    cwd는 대상 경로의 부모(그 파일이 속한 git repo) — REPO_ROOT로 고정하면 대상이
    중첩된 다른 저장소(예: 미러 클론)에 있을 때 REPO_ROOT 저장소의 .gitignore로 오판한다.

    결과를 캐싱한다 — 같은 폴더가 순회 판정 1회 + 상위 폴더의 하위목록 렌더 1회로
    두 번 불린다. 이 CLI는 1회성 프로세스라 실행 중 .gitignore가 바뀔 수 없으므로
    무효화할 근거가 없다(캐싱이 안전한 이유)."""
    parent = path.parent if path.parent.exists() else REPO_ROOT
    result = subprocess.run(
        ["git", "check-ignore", "-q", "--", str(path)],
        cwd=str(parent),
        check=False,
        capture_output=True,
    )
    return result.returncode == 0


def is_skipped_dir(d: Path) -> bool:
    """폴더를 순회·인덱스에서 건너뛸지 — 이름 규칙(시스템/사설) 또는 git-ignore(로컬 전용).

    gitignore된 폴더(로컬 스크래치 등)는 체크아웃마다 존재가 갈린다. 인덱스에 실으면
    그 폴더를 가진 사람과 아닌 사람이 서로 다른 README를 생성해 결과 자체가 오염되고,
    그 어긋남(drift)이 --check를 계속 비영으로 만들어 무관한 커밋까지 봉쇄한다.
    추적하지 않는(=관리 대상 아닌) 폴더는 생성·인덱스 양쪽에서 뺀다.

    (사고 원본: 형제 저장소에서 관측된 실사고 — gitignore된 스크래치 폴더를 인덱스
    대상으로 삼아 체크아웃마다 다른 README가 생성됐다.)"""
    return is_excluded_dir(d) or is_git_ignored(d)


def iter_folders(root: Path):
    """제외 규칙을 지키며 폴더를 재귀적으로 순회(루트 포함)."""
    yield root
    stack = [root]
    while stack:
        cur = stack.pop()
        try:
            children = sorted(
                [p for p in cur.iterdir() if p.is_dir() and not p.is_symlink()],
                key=lambda p: p.name,
            )
        except OSError as e:
            print(f"[warn] 폴더 읽기 실패로 건너뜀(검증 누락 가능): {cur} ({e})", file=sys.stderr)
            continue
        for child in children:
            if is_skipped_dir(child):
                continue
            yield child
            stack.append(child)


# 아카이브 폴더(`_manifest.md` 보유)에서 번호매김 원문(`NN-*.md`)을 가리는 패턴.
# 폴더별 build_index_block 호출마다 새로 컴파일하지 않도록 다른 컴파일 패턴들
# (_MARK_START_RE 등)과 같이 모듈 스코프로 둔다 — 동작 변화 없는 자리 이동.
_ARCHIVE_NUMBERED_RE = re.compile(r"^\d+[-_]")


def _collect_subdirs(folder: Path) -> list[tuple[Path, str | None]]:
    """인덱스에 실을 하위 폴더와 그 폴더 BLUF(이름순, 제외 규칙 적용).

    BLUF 읽기(파일 I/O)를 여기서 끝낸다 — 렌더 쪽이 읽으면 이 파일이 세운
    "수집이 I/O를 지고 렌더는 인자만 본다"가 한 축에서만 깨지고, 다음 사람이
    렌더를 부작용 없다고 오인해 재사용·캐싱 근거로 삼는다.
    """
    if not folder.is_dir():
        return []
    subdirs = sorted(
        [p for p in folder.iterdir() if p.is_dir() and not p.is_symlink() and not is_skipped_dir(p)],
        key=lambda p: p.name,
    )
    return [(d, readme_own_bluf(d)) for d in subdirs]


def _render_subfolder_section(subdirs: list[tuple[Path, str | None]]) -> list[str]:
    """'### 하위 폴더' 섹션 — 수집이 읽어 둔 BLUF를 한 줄씩 표시(순수)."""
    if not subdirs:
        return []
    lines = ["### 하위 폴더"]
    for d, bluf in subdirs:
        if bluf is None:
            desc = "(README 없음)"
        elif bluf.startswith(TODO_PREFIX):
            desc = f"_{bluf}_"
        else:
            desc = bluf
        lines.append(f"- `{d.name}/` — {desc}")
    lines.append("")
    return lines


def _collect_docs(folder: Path) -> list[Path]:
    """인덱스에 실을 문서 목록(README·에이전트 설정 제외, 텍스트 확장자만, 이름순)."""
    return sorted(
        [
            p for p in folder.iterdir()
            if p.is_file()
            and p.name != "README.md"
            and p.name not in AGENT_CONFIG_NAMES
            and p.suffix.lower() in TEXT_EXTS
        ],
        key=lambda p: p.name,
    ) if folder.is_dir() else []


def _partition_docs(docs: list[Path], is_archive: bool) -> tuple[list[str], int, list[Path]]:
    """문서 목록을 (일반 문서 항목, 아카이브 건수, BLUF 누락 문서)로 나눈다.

    이 저장소 관용구(check_doc_form.py의 검사 함수들)를 따라 인자를 변형하지
    않고 결과를 반환한다 — 호출자가 반환된 누락 목록을 자신의 missing에 합류시킨다.
    """
    doc_entries: list[str] = []
    archived = 0
    doc_missing: list[Path] = []
    for f in docs:
        if is_archive and _ARCHIVE_NUMBERED_RE.match(f.name):
            archived += 1
            continue  # 아카이브 원문: 개별 나열·BLUF 요구 생략(색인은 _manifest.md).
        bluf = extract_bluf(f)
        if bluf is None:
            # 메타(_로 시작)·비-md는 조용히 skip, 그 외 .md 문서는 BLUF 누락 보고.
            if f.suffix.lower() in {".md", ".markdown"} and not f.name.startswith("_"):
                doc_missing.append(f)
            continue
        doc_entries.append(f"- `{f.name}` — {bluf}")
    return doc_entries, archived, doc_missing


def _render_doc_section(doc_entries: list[str]) -> list[str]:
    """'### 문서' 섹션 — 일반 문서 항목을 그대로 나열."""
    if not doc_entries:
        return []
    return ["### 문서", *doc_entries, ""]


def _render_archive_section(is_archive: bool, archived: int) -> list[str]:
    """'### 원문 수집본' 섹션 — 아카이브 폴더에서 접힌 번호매김 문서 건수만 표시."""
    if not (is_archive and archived):
        return []
    return [
        "### 원문 수집본",
        f"- `NN-*.md` {archived}건 — 색인·fetch 결과는 `_manifest.md`, 실제 예시는 `_examples.md` 참조",
        "",
    ]


def _collect_assets(folder: Path) -> list[Path]:
    """인덱스에 실을 정보성 바이너리/자산 목록(gitignore 제외, 이름순)."""
    return sorted(
        [p for p in folder.iterdir()
         if p.is_file()
         and not p.is_symlink()
         and p.suffix.lower() in ASSET_EXTS
         and not is_git_ignored(p)],
        key=lambda p: p.name,
    ) if folder.is_dir() else []


def _render_asset_section(assets: list[Path]) -> list[str]:
    """'### 기타 파일 (BLUF 없음)' 섹션 — 같은 확장자 자산이 다수면 집약 표기."""
    if not assets:
        return []
    ext_counts = Counter(p.suffix.lower() for p in assets)
    collapsed: set[str] = set()
    asset_lines: list[str] = []
    for a in assets:
        ext = a.suffix.lower()
        if ext_counts[ext] >= _ASSET_COLLAPSE_MIN:
            if ext not in collapsed:
                collapsed.add(ext)
                asset_lines.append(f"- `*{ext}` {ext_counts[ext]}개")
        else:
            asset_lines.append(f"- `{a.name}`")
    return ["### 기타 파일 (BLUF 없음)", *asset_lines, ""]


def build_index_block(folder: Path, missing: list[Path]) -> str:
    """폴더의 하위 폴더/문서 BLUF를 모아 인덱스 블록 텍스트를 만든다.

    네 축(하위폴더/문서/아카이브 집약/자산 집약) 각각 "수집(파일시스템 I/O) →
    렌더(순수 문자열)" 두 단계로 뽑혀 있다 — 이 함수는 그 축들을 순서대로
    조립만 한다. 공개 시그니처(인자로 받은 missing을 변형)는 테스트가 부르므로
    그대로 유지한다.
    """
    subdirs = _collect_subdirs(folder)
    docs = _collect_docs(folder)

    # 아카이브 폴더(원문 수집본 색인 `_manifest.md` 보유): 번호 수집본은 BLUF 면제·집약 표기.
    is_archive = (folder / "_manifest.md").exists()
    doc_entries, archived, doc_missing = _partition_docs(docs, is_archive)
    missing.extend(doc_missing)

    assets = _collect_assets(folder)

    lines = [MARK_START]
    lines.extend(_render_subfolder_section(subdirs))
    lines.extend(_render_doc_section(doc_entries))
    lines.extend(_render_archive_section(is_archive, archived))
    lines.extend(_render_asset_section(assets))
    lines.append(MARK_END)
    return "\n".join(lines).rstrip() + "\n"


def handwritten_in_block(old_content: str) -> list[str]:
    """마커 블록 안에서 이 스크립트가 만들지 않은 줄을 찾는다.

    블록은 교체 대상이라 여기 있는 줄은 재생성 때 사라진다. 생성물은 형식이
    고정(`- \\`이름\\` — 설명` / `### 제목` / 빈 줄)이므로, 그 형식을 벗어난 줄은
    사람·에이전트가 손으로 넣은 것이다. 지우기 전에 멈추라고 이 목록을 쓴다.
    """
    start_m = _MARK_START_RE.search(old_content)
    if not start_m:
        return []
    end_m = _MARK_END_RE.search(old_content, start_m.end())
    if not end_m:
        return []
    inner = old_content[start_m.end():end_m.start()]
    return [
        line for line in inner.split("\n")
        if line.strip()
        and not line.startswith("- `")
        and not line.startswith("###")
    ]


def compose_readme(folder: Path, index_block: str) -> str:
    """기존 README의 수기 부분을 보존하며 인덱스 블록만 교체/삽입.

    비-UTF8 README는 `_read_readme`가 UnicodeDecodeError를 올린다 — 여기서
    삼키지 않고 호출측(main)에 전파해 쓰기 전에 건너뛰게 한다.
    """
    readme = folder / "README.md"
    label = folder.name if folder != REPO_ROOT else REPO_ROOT.name

    content = _read_readme(readme)
    if content is not None:
        start_m = _MARK_START_RE.search(content)
        end_m = _MARK_END_RE.search(content, start_m.end()) if start_m else None
        if start_m and end_m:
            head = content[:start_m.start()].rstrip()
            tail = content[end_m.end():].lstrip()
            parts = [head, "", index_block.rstrip()]
            if tail:
                parts += ["", tail.rstrip()]
            return "\n".join(parts).rstrip() + "\n"
        # 마커 없는 기존 README: 전체를 보존하고 인덱스 블록을 뒤에 덧붙인다(비파괴).
        return content.rstrip() + "\n\n" + index_block.rstrip() + "\n"

    # 신규 README: 폴더 목적 BLUF 자리(TODO)를 둔다.
    header = f"> **BLUF:** {TODO_PREFIX} — `{label}/` 폴더 목적을 한 줄로 채우세요."
    return header + "\n\n" + index_block.rstrip() + "\n"


def staged_folders(root: Path) -> list[Path]:
    """스테이징된 경로가 속한 폴더와 그 조상(루트까지)만 골라 반환한다.

    자동생성 인덱스는 폴더 README 하나가 그 폴더의 직속 자식(문서·자산·하위폴더의
    자체 BLUF)에서만 파생된다 — 그래서 스테이징한 변경이 바꿀 수 있는 README는
    그 경로의 **조상 폴더**에만 있다(직속 자식 파일 추가·삭제, 새 하위폴더 생성,
    하위 README의 자체 BLUF 변경이 모두 조상 폴더 README에서 걸린다). 전체 스캔
    대신 이 집합만 검사하면, 다른 병렬 레인이 건드린 무관한 폴더의 어긋남이 이번
    커밋을 막지 않는다.

    (사고 원본: 형제 저장소에서 관측된 실사고 — 1차: 다른 레인의 새 문서가 반영 안
    된 인덱스가 무관한 커밋을 봉쇄. 2차: 다른 슬라이스의 BLUF 변경이 tests/README에
    어긋남으로 걸림.)

    **대가(정직 표기)**: 손대지 않은 폴더의 선재 어긋남은 이 경로로 안 잡힌다.
    그 백스톱이 될 수 있는 것은 전체 스캔 `--check`뿐이다 — 다만 이 패키지는
    그 배선을 강제하지 않는다. 채택 저장소가 출하 검사·CI·주기 실행 등 별도
    지점에 전체 스캔을 스스로 걸어야만 그 백스톱이 실제로 성립한다(배선 의무는
    `docs/adopting.md` 참고). 안 걸면 손대지 않은 폴더의 어긋남은 아무 데서도
    안 잡힌다. `check-doc --staged`가 손댄 줄만 강제하는 것과 같은 diff-스코프
    관용구다.

    삭제(D)·개명(R)·복사(C)도 포함한다 — 파일이 사라지거나 옮겨지면 관련 폴더
    README의 문서 목록이 바뀌므로 그 폴더도 재검사 대상이다(추가만 보면 삭제로
    생긴 어긋남을 놓쳐 검사에 구멍이 난다). 개명·복사는 옛/새 경로 양쪽 폴더가
    영향받으므로 둘 다 담는다.

    **파일명에 탭·백슬래시·큰따옴표가 있으면 git이 `core.quotepath` 설정과
    무관하게 그 경로를 C 방식으로 quote한다** — 탭 구분 출력(`--name-status`
    기본형)에서 그 quote·이스케이프를 풀지 않고 `parts[1]`을 그대로 쓰면
    존재하지 않는 경로가 되어, 그 경로가 진짜 속한 폴더가 조상 집합에서
    조용히 빠진다(검사가 그 폴더를 못 보고도 통과해버린다). `-z`(NUL 구분자)를
    쓰면 quote 자체가 나오지 않아 이 문제가 근본에서 없어진다 — 그래서
    `core.quotepath=false`도 더는 필요 없다(그 설정은 비ASCII만 다루고, 이
    특수문자 quote는 애초에 그것과 무관했다).
    """
    out = subprocess.run(
        ["git", "diff", "--cached", "--name-status", "-M", "-C",
         "--diff-filter=ACMRD", "-z"],
        cwd=str(root), capture_output=True, text=True, check=False,
    ).stdout
    # -z 출력은 NUL로 이어진 토큰열이다 — "줄"이 없다. 상태 토큰 하나에 경로
    # 토큰이 하나(A/M/D) 또는 둘(R/C, 옛·새 경로) 뒤따르는 형태를 순서대로
    # 소비한다. 마지막 토큰은 트레일링 NUL이 만든 빈 문자열이라 버린다.
    tokens = out.split("\0")
    if tokens and tokens[-1] == "":
        tokens.pop()
    dirs: set[Path] = set()
    i = 0
    while i < len(tokens):
        status = tokens[i]
        i += 1
        if status[:1] in ("R", "C"):
            # R(개명)·C(복사)는 옛·새 경로 둘 다 폴더가 영향받는다.
            if i + 1 >= len(tokens):
                break  # 토큰열이 짝 없이 끊겼다 — 더 못 읽으므로 여기서 멈춘다.
            rels = tokens[i:i + 2]
            i += 2
        else:
            if i >= len(tokens):
                break  # 상태 토큰 뒤에 경로가 안 왔다 — 더 못 읽으므로 멈춘다.
            rels = tokens[i:i + 1]
            i += 1
        for rel in rels:
            d = (root / rel).parent
            while True:
                dirs.add(d)
                if d == root or root not in d.parents:
                    break
                d = d.parent
    # 존재하고 순회 대상인 폴더만 검사한다(삭제된 폴더 자신은 빠져도 그 부모가
    # 집합에 있어, 부모 README 재생성이 사라진 하위폴더 항목을 제거한다). 루트는
    # 스테이징이 하나라도 있으면 항상 포함(모든 경로의 조상이라 이미 집합에 있다).
    return sorted(d for d in dirs if d == root or (d.is_dir() and not is_skipped_dir(d)))


def _print_duplicate_markers_abort(
    duplicated: list[tuple[Path, int, int]], root: Path
) -> None:
    """마커 쌍(START/END)이 온전한 한 쌍이 아닌 README들에 대한 중단 안내.

    처방은 두 경우가 다르다 — 여분을 지우는 것과 짝을 맞추는 것. 한 문구로
    뭉뚱그리면 짝이 없어 걸린 사람이 "지울 여분"을 찾다 헤맨다.
    """
    print("\n[gen_readmes] 중단 — 자동생성 마커가 온전한 한 쌍이 아니다.",
          file=sys.stderr)
    print("  쌍이 여럿이면 첫 쌍만 갱신돼 나머지가 낡은 채 남고, 짝이 안 맞으면",
          file=sys.stderr)
    print("  고아 마커 뒤에 새 블록이 덧붙는다. 둘 다 쓰기 전에 멈췄다.",
          file=sys.stderr)
    for p, n_start, n_end in duplicated:
        if n_start > 1 or n_end > 1:
            fix = "여분의 블록을 지워 한 쌍만 남겨라(어느 쪽이 최신인지는 기계가 못 가린다)"
        else:
            fix = "짝 없는 마커를 지우거나 빠진 짝을 채워 한 쌍으로 만들어라"
        print(f"  {p.relative_to(root).as_posix()} — START {n_start}회, END {n_end}회"
              f"\n    → {fix}", file=sys.stderr)
    print("\n  정리한 뒤 이 명령을 다시 돌려라.", file=sys.stderr)


def _print_handwritten_abort(doomed: list[tuple[Path, list[str]]], root: Path) -> None:
    """자동생성 블록 안에 손으로 쓴 줄이 있는 README들에 대한 중단 안내.

    쓰고 나서 알리면 이미 지워진 뒤라 알림이 소용없다 — 이 함수는 아무것도
    쓰지 않은 상태에서 무엇이 사라질지·어디로 옮길지를 알리기만 한다.
    """
    print("\n[gen_readmes] 중단 — 자동생성 블록 안에 손으로 쓴 줄이 있다.",
          file=sys.stderr)
    print("  재생성하면 아래 줄들이 사라진다. 지우기 전에 멈췄다.",
          file=sys.stderr)
    for p, lines in doomed:
        print(f"\n  {p.relative_to(root).as_posix()}", file=sys.stderr)
        for line in lines:
            print(f"      {line}", file=sys.stderr)
    print("""
  줄이거나 형식을 고치지 마라 — **먼저 어디로 갈지 정하라.** 목적지가 그 자리의
  상한을 정하므로, 목적지 없이 축약하면 형식이 안 맞아 또 고치게 된다.

  그 내용이 특정 문서에 관한 것이면
      → 그 문서의 BLUF 한 줄을 고쳐라. 인덱스는 거기서 파생된다.
  이 폴더 자체의 목적이면
      → README 맨 위 BLUF 한 줄에 써라(블록 밖이라 재생성이 보존한다).
  둘 다 아니면
      → README에 있을 내용이 아니다. 원본 문서 본문으로 옮겨라.

  옮긴 뒤 이 명령을 다시 돌려라.""", file=sys.stderr)


def _print_write_failure(
    readme: Path,
    e: OSError,
    written: list[Path],
    pending: list[tuple[Path, str]],
    root: Path,
) -> None:
    """쓰기 도중 OS 오류가 난 지점을 보고 — 어디까지 썼고, 무엇을 못 썼는지.

    손글씨 검사는 전체를 먼저 훑고 판정해 반쪽 실행을 막지만, 파일시스템
    오류(권한 등)는 그 보호 밖이다. 이미 써진 파일은 되돌리지 않는다 — 각
    파일은 원자적으로 교체되므로(`_write_readme_atomically`) 완성된 결과이지
    반쪽이 아니다. 즉 남는 것은 "일부 폴더만 갱신됨"이지 "깨진 파일"이 아니다.
    """
    not_written = [r for r, _ in pending if r not in written]
    print(f"\n[gen_readmes] 쓰기 실패 — {len(written)}/{len(pending)}개 완료 후 중단: "
          f"{readme.relative_to(root).as_posix()} ({e})", file=sys.stderr)
    if written:
        print("  이미 써진 파일(반쪽 실행 — 롤백하지 않음):", file=sys.stderr)
        for p in written:
            print(f"    - {p.relative_to(root).as_posix()}", file=sys.stderr)
    print("  못 쓴 파일:", file=sys.stderr)
    for p in not_written:
        print(f"    - {p.relative_to(root).as_posix()}", file=sys.stderr)


def _print_summary(
    root: Path,
    changed: list[Path],
    missing_bluf: list[Path],
    todo_folders: list[Path],
    check: bool,
) -> None:
    """최종 리포트 출력 — 변경/누락/TODO 현황을 사람이 읽을 형태로 나열.

    DRIFT 반환 여부 판정은 이 함수 밖 main()의 몫이다(표시와 판단을 분리).
    """
    # 국소 concise 헬퍼(lambda 대입) — E731은 이 레포 관례대로 전역 ignore가 아니라
    # 그 줄에서 인라인 면제한다(pyproject `[tool.ruff.lint]` 주석 참조).
    rel = lambda p: p.relative_to(root).as_posix()  # noqa: E731
    print(f"[gen_readmes] 루트: {root}")
    print(f"  변경{'(필요)' if check else ''} README: {len(changed)}")
    for p in changed:
        print(f"    ~ {rel(p)}")
    if missing_bluf:
        print(f"  BLUF 누락 문서(.md): {len(missing_bluf)}")
        for p in sorted(set(missing_bluf)):
            print(f"    ! {rel(p)}")
    if todo_folders:
        print(f"  폴더 목적 BLUF 미작성(README 상단 TODO): {len(todo_folders)}")
        for p in todo_folders:
            print(f"    ? {rel(p) if p != root else '.'}")


def main(argv: list[str] | None = None, prog: str | None = None) -> int:
    ap = argparse.ArgumentParser(prog=prog, description="BLUF 기반 README 자동 생성기")
    ap.add_argument("--check", action="store_true",
                    help="드라이런: 변경 필요/누락 BLUF가 있으면 비영 종료(파일 미수정)")
    ap.add_argument("--staged", action="store_true",
                    help="스테이징된 경로가 속한 폴더(+조상)만 대상 — 병렬 레인의 무관한 "
                         "어긋남으로 커밋이 막히지 않게 좁힌다. pre-commit 훅용.")
    ap.add_argument("--root", default=None,
                    help="저장소 루트 경로(기본: 대상 저장소 git 루트)")
    args = ap.parse_args(argv)

    # 기본 루트 = 대상 저장소 git 루트. 설치형 CLI로 남의 repo에서 돌 때 번들
    # 패키지 위치(REPO_ROOT=src/)가 아니라 그 저장소를 대상으로 삼아야 한다 —
    # check-pr·check-doc과 같은 target_root()로 대상 탐색을 단일화한다.
    root = Path(args.root).resolve() if args.root else target_root()
    changed: list[Path] = []
    missing_bluf: list[Path] = []
    todo_folders: list[Path] = []
    doomed: list[tuple[Path, list[str]]] = []
    duplicated: list[tuple[Path, int, int]] = []
    pending: list[tuple[Path, str]] = []

    folders = staged_folders(root) if args.staged else iter_folders(root)
    for folder in folders:
        index_block = build_index_block(folder, missing_bluf)
        readme = folder / "README.md"

        if readme.is_symlink():
            # 링크를 따라가 그 원본을 덮어쓰면 폴더 밖 파일이 변형된다 — 쓰지
            # 않되 조용히 넘어가지는 않는다(이 저장소는 조용한 폴백을 금한다).
            print(f"[warn] README가 심볼릭 링크라 건너뜀(원본 보호): {readme}",
                  file=sys.stderr)
            continue

        try:
            old_content = _read_readme(readme)
            if old_content is not None:
                n_start, n_end = marker_occurrences(old_content)
                # 정상은 둘뿐이다 — 블록이 없거나(0,0), 온전한 한 쌍(1,1).
                # 나머지는 전부 이상이다. 쌍이 여럿인 경우만 막으면 짝이 안 맞는
                # 파손 문서(START만·END만)가 그대로 통과해, 고아 마커 뒤에 새 블록이
                # 덧붙고 rc는 0이 된다 — 그 상태는 다음 실행에서야 걸리고 그 사이
                # 커밋된다. 짝이 안 맞는 것도 사람이 봐야 할 상태다.
                if (n_start, n_end) not in {(0, 0), (1, 1)}:
                    duplicated.append((readme, n_start, n_end))
                    continue
                hand = handwritten_in_block(old_content)
                if hand:
                    doomed.append((readme, hand))
            new_content = compose_readme(folder, index_block)
        except UnicodeDecodeError as e:
            # errors="replace"로 읽어 그대로 되쓰면 원본 바이트(CP949 한글 등)가
            # 대체문자로 굳어 영구 손상된다 — 엄격 디코드 실패는 건너뛴다.
            print(f"[warn] README가 UTF-8이 아니라 건너뜀(재저장 시 손상 방지): "
                  f"{readme} ({e})", file=sys.stderr)
            continue

        if old_content != new_content:
            changed.append(readme)
            pending.append((readme, new_content))

        if f"**BLUF:** {TODO_PREFIX}" in new_content:
            todo_folders.append(folder)

    # 마커 쌍(START/END)이 한 README에 2개 이상이면 **아무것도 쓰지 않고 멈춘다.**
    # split(...,1) 방식(과거 코드·compose_readme 둘 다 첫 쌍만 본다)으로 그냥
    # 진행하면 첫 쌍만 갱신되고 나머지는 낡은 채 영구 방치되는데, 그 상태를
    # --check가 "이상 없음"이라 오판한다 — 어느 쌍이 최신인지는 기계가 못
    # 가리므로 사람이 정리한 뒤 다시 돌리게 한다.
    if duplicated:
        _print_duplicate_markers_abort(duplicated, root)
        return DUPLICATE_MARKERS

    # 손으로 쓴 줄이 하나라도 블록 안에 있으면 **아무것도 쓰지 않고 멈춘다.**
    # 쓰고 나서 알리면 이미 지워진 뒤라 알림이 소용없다 — 파괴는 되돌릴 수
    # 있어야 알림이 값어치를 갖는다. 스캔을 다 돌린 뒤 판정하는 이유는, 한
    # 폴더가 걸렸는데 앞 폴더는 이미 써버리는 반쪽 실행을 막기 위해서다.
    if doomed:
        _print_handwritten_abort(doomed, root)
        return HANDWRITTEN_ABORT

    if not args.check:
        written: list[Path] = []
        try:
            for readme, new_content in pending:
                _write_readme_atomically(readme, new_content)
                written.append(readme)
        except OSError as e:
            # 손글씨 검사는 전체를 먼저 훑고 판정해 반쪽 실행을 막지만, 파일시스템
            # 오류(권한 등)는 그 보호 밖이다 — 잡아서 어디까지 썼는지 보고하고,
            # 파이썬 기본 크래시 종료코드(1)로 죽으면 DRIFT와 겹치므로 이름 붙은
            # 코드로 끝낸다.
            _print_write_failure(readme, e, written, pending, root)
            return WRITE_FAILURE

    # ── 리포트 ────────────────────────────────────────────────────────────────
    _print_summary(root, changed, missing_bluf, todo_folders, args.check)

    if args.check and (changed or missing_bluf):
        print("[gen_readmes] --check: 갱신 필요 또는 BLUF 누락 존재 → 비영 종료")
        return DRIFT
    return 0


if __name__ == "__main__":
    sys.exit(main())
